### ISSUE TITLE
Refactor Story View into a React component

### ISSUE THREAD

**Issue by marcosjr182** [Codeminer42/cm42-central#183]
Story View (`story_view.js`) is being gradually converted into a react component.

Here is the current state:
#### Expanded
- [x] ~~Control buttons ('Save','Delete', 'Cancel')~~ (#131)
- [x] ~~'Copy id/url to clipboard' and History buttons~~ (#162)
- [x] ~~Estimate selector~~ (#171)
- [x] ~~State and Type selectors~~ (#190, #189)
- [x]  ~~_Requested by_ and _Owned by_ select~~ (#196, #197)
- [x] ~~Labels~~ (#206)
- [x] ~~Description~~ (#212)
- [x] ~~Tasks~~ (#210)
- [x] ~~Attachments~~ (#215)
- [x] ~~Notes~~ (#192)

#### Collapsed
- [ ] State related action buttons
- [ ] Collapsed template (`story.ejs`)

#### Popup
- [ ] `hoverBox` template (`story_hover.js`)

#### Wrap up

- [ ] Convert story_view into a React component removing all the appends and replacing all the appends with actual components being rendered inside other components. It can be a `<Story />` component that stores the open/closed state in component's state and then renders `<OpenStory />` and `<ClosedStory />` conditionally
- [ ] Move mutability operations calls to an upper component (probably a container component) that will handle the changes and re-render the component

**Comment by talyssonoc** [comment]
Near to the end of this migration it'll be necessary to change the approach of [bindElementToAttribute](https://github.com/Codeminer42/cm42-central/blob/master/app/assets/javascripts/views/form_view.js#L119). I suggest using two-way-data-binding with the component state (using [linkstate](https://www.npmjs.com/package/linkstate)).
